### ISSUE TITLE
Missing ICE Lite support

### ISSUE THREAD

**Issue by ibc** [shinyoshiaki/rainy-ice#3]
Lack of ICE Lite support means that this library can not be used to establish a ICE+DTLS connection with ICE Lite servers.

If you add support for ICE Lite I'll test this lib extensively against [mediasoup](https://mediasoup.org) and will make a handler to use it within mediasoup-client in Node (as we did for Python aiortc lib):

* https://github.com/versatica/mediasoup-client-aiortc/

BTW here the commit in which `aioice` added support for ICE Lite:

* https://github.com/aiortc/aioice/commit/e5c911c1aebcb51ce4ecdd243c8f00578bc3c222

**Comment by shinyoshiaki** [comment]
I'll add it to my todo list.

**Comment by shinyoshiaki** [comment]
I followed the aiortc implementation and added iceLite support.

However, we have not tested it to communicate with the actual IceLite agent, so we cannot guarantee that it will work.

I'll close this Issue, but if there is a problem,please create the Issue again

**Comment by ibc** [comment]
Great, thanks. Will test as far as I can.
